---
- name: Gather VMware information
  hosts: esxi
  tasks:
  - name: Get VM information
    community.vmware.vmware_vm_info:
       hostname: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_pass }}"
       validate_certs: false
    delegate_to: localhost
    register: vm_info
  - name: Print all VM information
    debug:
      msg: "{{ item.guest_fullname }}"
    loop: "{{ vm_info.virtual_machines }}"
