---
- name: Gather VMware information
  hosts: esxi
  tasks:
  - name: Get VM information
    community.vmware.vmware_guest_info:
       hostname: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_pass }}"
       datacenter: ha-datacenter
       validate_certs: false
       name: rhelgen001
    delegate_to: localhost
    register: vm_info
  - name: Print return VM values.
    debug:
      msg: 
      - "{{ vm_info.instance.hw_guest_full_name }}"
      - "{{ vm_info.instance.hw_name }}"
      - "{{ vm_info.instance.hw_guest_id }}"
      - "{{ vm_info.instance.hw_memtotal_mb }}"
      - "{{ vm_info.instance.hw_power_status }}"
      - "{{ vm_info.instance.ipv4 }}"

