---
- name : Declare hosts
  hosts: esxi
  tasks:
  - name: Create a virtual machine on given ESXi hostname
    community.vmware.vmware_guest:
          name: ubunweb001
          state: poweredon
          guest_id: ubuntu64Guest
          datacenter: ha-datacenter
          hostname: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_pass }}"
          validate_certs: false
          folder: /ha-datacenter/vm
          disk:
                  - size_gb: 20
                    type: thin
                    datastore: datastore3
          hardware:
                  memory_mb: 1024
                  num_cpus: 2
                  hotadd_cpu: True
                  hotremove_cpu: True
                  boot_firmware: efi
          cdrom:
            - controller_number: 0
              unit_number: 0
              state: present
              type: iso
              iso_path: "{{ ansible_ubun_iso }}"
          networks:
                  - name: VM Network
                    ip: 192.168.1.156
                    netmask: 255.255.255.0
                    device_type: vmxnet3
    delegate_to: localhost
    register: deploy_vm
  - name: Print the variables.
    debug:
      var: deploy_vm

